---
- hosts: master
  become_user: ubuntu
  tasks:
  - name: showing the output
    shell: |
       kubectl get nodes
       kubectl get nodes -o wide

- hosts: master
  become_user: ubuntu
  tasks:
  - name: cloning the repo
    git:
      repo: https://github.com/singaravellu/game-of-life.git
      dest: /home/ubuntu/game-of-life
  - name: executing the kubectl commands
    shell: |
      cd game-of-life
      kubectl apply -f Deployment.yml
      kubectl apply -f service.yml
      cd ~
      kubectl get svc
